name: Deploy GitHub Pages (step-4)

on:
  push:
    branches:
      - step-4-setup-github-actions

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (src)
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'src'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4